# Effect
blur=1
blur_layer=1
blur_optimized=1
blur_params_num_passes=1
blur_params_radius=3
blur_params_noise=0.0117
blur_params_brightness=0.8172
blur_params_contrast=0.8916
blur_params_saturation=1.0

shadows=0
layer_shadows=0
shadow_only_floating=1

border_radius=10
no_radius_when_single=0
focused_opacity=1.0
unfocused_opacity=1.0

# Animation Configuration
animations=1
layer_animations=1
animation_type_open=zoom
animation_type_close=zoom
layer_animation_type_open=fade
layer_animation_type_close=fade
animation_fade_in=1
animation_fade_out=1
tag_animation_direction=1
zoom_initial_ratio=0.8
zoom_end_ratio=1.0
fadein_begin_opacity=0.5
fadeout_begin_opacity=0.8
animation_duration_move=350
animation_duration_open=300
animation_duration_tag=300
animation_duration_close=300
animation_duration_focus=250
animation_curve_open=0.05,0.9,0.1,1.05
animation_curve_move=0.05,0.9,0.1,1.05
animation_curve_tag=0.25,1.0,0.5,1.0
animation_curve_close=0.25,1.0,0.5,1.0
animation_curve_focus=0.25,1.0,0.5,1.0
animation_curve_opafadeout=0.25,1.0,0.5,1.0
animation_curve_opafadein=0.25,1.0,0.5,1.0

# Layout
new_is_master=0
smartgaps=0
default_mfact=0.55
default_nmaster=1

# Misc
xwayland_persistence=1
enable_hotarea=0
syncobj_enable=0
no_border_when_single=0
axis_bind_apply_timeout=100
focus_on_activate=1
sloppyfocus=1
warpcursor=1
focus_cross_monitor=0
focus_cross_tag=0
circle_layout=tile,scroller
enable_floating_snap=1
snap_distance=50
cursor_size=24
cursor_theme=Adwaita
cursor_hide_timeout=0
drag_tile_to_tile=1
single_scratchpad=1

# keyboard
repeat_rate=25
repeat_delay=600
numlockon=1
xkb_rules_layout=us,de
xkb_rules_options=grp:alt_space_toggle

# Trackpad
disable_trackpad=0
tap_to_click=1
tap_and_drag=1
drag_lock=1
mouse_natural_scrolling=0
trackpad_natural_scrolling=1
disable_while_typing=1
left_handed=0
middle_button_emulation=0
swipe_min_threshold=1
accel_profile=2
accel_speed=0.0

# Appearance
gappih=5
gappiv=5
gappoh=10
gappov=10
scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
borderpx=2
rootcolor=0x201b14ff
bordercolor=0x444444ff
focuscolor=0x8BAA9Bff
maximizescreencolor=0xBABD2Cff
urgentcolor=0xad401fff
scratchpadcolor=0xc4939dff
globalcolor=0x8d64cfff
overlaycolor=0x95C381ff

source=./env.conf
source=./bind.conf
source=./rule.conf
source=./monitor.conf
source=./tag.conf

exec-once=~/.config/mango/autostart.sh
