# Tag labels
# set_tag_name=1,一
# set_tag_name=2,二
# set_tag_name=3,三
# set_tag_name=4,四
# set_tag_name=5,五
# set_tag_name=6,六
# set_tag_name=7,七
# set_tag_name=8,八
# set_tag_name=9,九
# set_tag_name=10,十
